// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnZT1evDdhAuQRJthTLNEvdN6tVoDuPyc',
    appId: '1:476299870459:web:f3df02d9ef4b01e236f05e',
    messagingSenderId: '476299870459',
    projectId: 'meongbti-1e3c0',
    authDomain: 'meongbti-1e3c0.firebaseapp.com',
    storageBucket: 'meongbti-1e3c0.appspot.com',
    measurementId: 'G-6WP72M050P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoilX-sd-azdpvRi0D-ezgdak62c26PE4',
    appId: '1:476299870459:android:b9ac238f598b1a3f36f05e',
    messagingSenderId: '476299870459',
    projectId: 'meongbti-1e3c0',
    storageBucket: 'meongbti-1e3c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJtdYHtC11CdIOmHMPhUjf5b6q9FE6Ips',
    appId: '1:476299870459:ios:ba37e45908dd8af636f05e',
    messagingSenderId: '476299870459',
    projectId: 'meongbti-1e3c0',
    storageBucket: 'meongbti-1e3c0.appspot.com',
    iosBundleId: 'com.soojin.meongbti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJtdYHtC11CdIOmHMPhUjf5b6q9FE6Ips',
    appId: '1:476299870459:ios:2aa9a80ad6fa84cf36f05e',
    messagingSenderId: '476299870459',
    projectId: 'meongbti-1e3c0',
    storageBucket: 'meongbti-1e3c0.appspot.com',
    iosBundleId: 'com.soojin.meongbti.RunnerTests',
  );
}
